
node-dev:
    build: .
    ports:
        - "3000:3000"
    links: 
        - mongo
    volumes:
        - /Users/traveler/code/mongotest/data/db:/data/db/
mongo: 
    image: mongo
    ports: 
        - "27017:27017"