
node-dev:
    build: .
    ports:
        - "3000:3000"
    links:
        - mongo
    volumes:
        - /c/Users/ben/code/docker-play/data/db:/data/db/
mongo:
    image: mongo
    ports:
        - "27017:27017"
